version: '3'

services:
  easybuggy:
    image: openjdk:17-oracle
    volumes:
      - ./project_target/${PROJECT_NAME}:/app/project.jar
    working_dir: /app
    command: ["java", "-jar", "project.jar"]
    ports:
      - "3000:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "${HEALTH_CHECK_URL}"]
      interval: 10s
      timeout: 1s
      retries: 30
  checkmarx-dast:
    image: checkmarx/dast:latest
    environment:
      - CX_APIKEY=${APIKEY}
    volumes:
      - ./project_target:/dast
    command: >
      api 
      --environment-id=${ENVIRONMENT_ID}
      --config=/dast/${CONFIG_NAME}
      --base-url=${BASE_URL}
      --verbose
      --retry=3
      --retry-delay=20
      --openapi /dast/${OPENAPI_NAME}
    depends_on:
      easybuggy:
        condition: service_healthy
